### PR TITLE
Add Gallium XA toggle

### PR DESCRIPTION
**Pull request by Faalagorn**
Added toggle to enable/disable Gallium XA tracker – disabling it allows me to skip building some drivers that I don't need saving time and space, so might be useful. :)

While at it, I made slight adjustments to the comments in `customization.cfg`.

### CODE REVIEW

**Comment by Tk-Glitch** [comment]
With the naming scheme changes upstream lately which seems to affect that specific variable, we'd want it to switch between `${_enabled_}` and `${_disabled_}` instead of a possibly deprecated user-defined value.

**Comment by Faalagorn** [comment]
> With the naming scheme changes upstream lately which seems to affect that specific variable, we'd want it to switch between `${_enabled_}` and `${_disabled_}` instead of a possibly deprecated user-defined value.

Thanks! Can you point me to that change? Was a while and I'm not following the changes in mesa as closely lately, but maybe I can get it to work for me then and only compile what I need :)

**Comment by Tk-Glitch** [comment]
The related commit on my end is https://github.com/Frogging-Family/mesa-git/commit/79c28cbe171696cf244fd9fb1679685f605425e5

On the mesa side it was https://gitlab.freedesktop.org/mesa/mesa/-/commit/138c003d22739b0d1e6860ed398dd511a44cde04

So something like this or similar would do:
```
if [ "$_gallium_xa" = "false" ] || [ "$_gallium_xa" = "disabled" ]; then
  _gallium_xa="${_disabled_}"
else
  _gallium_xa="${_enabled_}"
fi
```

**Comment by Tk-Glitch** [comment]
I'll add the aforementioned fix on my end

**Comment by Faalagorn** [comment]
Thanks! :green_heart:

**Pull request merged**
